dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=docker setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: i/3I4RP9aUzh/gwZ3Ad4H2lYI3Qv+R1DXsWJouDt8Jgsg3wFYoSaRKrJPdp2OjqHLCYOPY8NuH6h1QKxfoh60exfc/lv6AMfQzfRjfZftCqFO0fHdpbf305eVEwi10Vz6OTDzoCstLa5jTr38RPxUi2+nzZ7Woo3zXG4IbN+GY57w8BkH0NIaf6WFDexoW6RQTvlSd6OkSIYUjXAW2+ti98keYG5FF5KMZLAvEqG2HOqnrXP9ei7bhgrnCIMUa3E7BnNLcWyGbNu0G9G9keJcGAojpaqjk0WxJhK3DX1htl+ZRblvOQsq0KKRBxlHMmNhr1FNDRE3bRDPaZgEzcQUT1P4zrTExpkR5xHGBqWJRdHqKNzxo7by80IXKuImL5MA08cVl8Sm7OVWFe5vDEl4Aqn29gJ4a/v+2j1ZWVf5RKvTpx+vNwwUAbPtaiqbIpZGy6yPps0NTVYOBDr5uTtV99ua/c1krzRYzS5QSzrqqOVdc4LnAgfiBjJGWxcenrqThNiTyjLoauu/tyadBBoBIMnOrHdWNZwKburluNyhIKA2I2+IAQ5u0JTBwhOmPNUutHVSCBwhNnzDKS5Gp5L25mJ7rk875A7eR4vomVP2W9tn3+scj4fYsGt66QNvHViJ+8GUTG6y80kMonnT88yhGbcE88lZCwivANz/xrDXhg=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
